# Generated by Django 4.1.3 on 2022-12-13 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='user_first',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myRelationships1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationship',
            name='user_second',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myRelationships2', to=settings.AUTH_USER_MODEL),
        ),
    ]
