# Generated by Django 4.1.3 on 2023-01-10 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0002_rating_review_rating_subject_alter_rating_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('rated', 'Rating'), ('reviewed', 'Review'), ('Add to List', 'Add to List'), ('Watched', 'Watched')], default='rated', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='listitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watching.listitem'),
        ),
        migrations.AddField(
            model_name='activity',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watching.rating'),
        ),
        migrations.AddField(
            model_name='activity',
            name='subject',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='myActivity', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='when',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
