# Generated by Django 4.1.3 on 2023-01-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0002_rating_review_rating_subject_alter_rating_user'),
        ('friends', '0003_activity_action_activity_listitem_activity_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watching.list'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('rated', 'Rating'), ('reviewed', 'Review'), ('Add to List', 'Add to List'), ('Watched', 'Watched'), ('Created list', 'Created new list')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activity',
            name='subject',
            field=models.IntegerField(null=True),
        ),
    ]
