# Generated by Django 4.1.3 on 2023-01-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_activity_list_alter_activity_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('Rate', 'Rated'), ('Review', 'Reviewed'), ('List', 'Updated a list'), ('Watch', 'watched'), ('newlist', 'created new list, ')], max_length=30),
        ),
    ]
