# Generated by Django 4.1.3 on 2022-11-09 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='name',
            field=models.CharField(default='Test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mylists', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listitem',
            name='item',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listitem',
            name='list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='watching.list'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listitem',
            name='name',
            field=models.CharField(default='Test', max_length=200),
            preserve_default=False,
        ),
    ]
