# Generated by Django 4.1.3 on 2022-11-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0002_list_name_list_owner_listitem_item_listitem_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
