# Generated by Django 4.1.3 on 2022-11-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0003_list_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('M', 'Movie'), ('S', 'Show')], max_length=20)),
                ('poster', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='listitem',
            name='type',
            field=models.CharField(choices=[('M', 'Movie'), ('S', 'Show')], default='movie', max_length=20),
            preserve_default=False,
        ),
    ]
