# Generated by Django 4.1.3 on 2023-01-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0003_rating_name_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='subjecttype',
            field=models.CharField(choices=[('M', 'Movie'), ('S', 'Show')], default='M', max_length=20),
            preserve_default=False,
        ),
    ]
