# Generated by Django 4.1.3 on 2023-01-26 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0004_rating_subjecttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='poster',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listitems', to='watching.list'),
        ),
    ]
